logger:
  level: 'info'  #("debug", "info", "warn", "error", "dpanic", "panic", "fatal")
storage:
  type: postgres
http:
  addr: ':8080'
grpc:
  addr: ':50051'
postgres:
  dsn: 'postgres://postgres:passpass@localhost:5432/postgres?sslmode=disable'
  poolMax: 2
