scheduler:
  deletePeriod: 525600 # delete events happened 60 * 24 * 365 minutes ago (1 year)
rabbitmq:
  addr: "amqp://guest:guest@rabbitmq/"
  exchange: calendar
  exchangeType: direct
  queue: notifications
  consumerTag: calendar-consumer
  bindingKey: calendar-key
  reliable: true
  persistent: true