sender:
rabbitmq:
  addr: "amqp://guest:guest@rabbitmq/"
  exchange: calendar
  exchangeType: direct
  queue: notifications
  consumerTag: calendar-consumer
  bindingKey: calendar-key
  reliable: true
  persistent: true